configfile: "config.yaml"

import os
import glob

SAMPLES = "/Users/angelol/Documents/PhD/BE-VCF/data/Christos/raw_reads/*"
SAMPLES = sorted([os.path.splitext(val)[0] for val in (glob.glob(SAMPLES))]) #Remove .gz from filename path
SAMPLES = [os.path.splitext(val)[0] for val in SAMPLES]
SAMPLES = [os.path.basename(val) for val in SAMPLES]

for i, s in enumerate(SAMPLES):
    SAMPLES[i] = SAMPLES[i][:-3] # Remove _1 or _2 suffix for paired-end reads

SAMPLES = list(set(SAMPLES))

rule all:
    input:
        "plots/quals.svg"

rule qual_filter:
    input:
        R1 = config["paths"]["raw_reads"] + "{sample}_R1.fastq",
        R2 = config["paths"]["raw_reads"] + "{sample}_R2.fastq"
    output:
        R1 = "data/" + "{sample}_R1.fastq",
        R2 = "data/" + "{sample}_R2.fastq"
    shell:
        "fastp --thread 8 --correction --in1 {input.R1} --in2 {input.R2} --out1 {output.R1} --out2 {output.R2}"

rule bwa_map:
    input:
        template = "data/template.fa",
        R1 = "data/" + "{sample}_R1.fastq",
        R2 = "data/" + "{sample}_R2.fastq"
    output:
        "mapped_reads/{sample}.bam"
    shell:
        "bwa mem -t 4 {input.template} {input.R1} {input.R2} | samtools view -Sb - > {output}"

rule samtools_sort:
    input:
        "mapped_reads/{sample}.bam"
    output:
        "sorted_reads/{sample}.bam"
    shell:
        "samtools sort -T sorted_reads/{wildcards.sample} "
        "-O bam {input} > {output}"

rule samtools_index:
    input:
        "sorted_reads/{sample}.bam"
    output:
        "sorted_reads/{sample}.bam.bai"
    shell:
        "samtools index {input}"

rule bcftools_call:
    input:
        fa = "data/template.fa",
        bam = expand("sorted_reads/{sample}.bam", sample=SAMPLES),
        bai = expand("sorted_reads/{sample}.bam.bai", sample=SAMPLES)
    output:
        "calls/all.vcf"
    shell:
        "freebayes --min-alternate-count 1 --min-alternate-fraction 0 -f {input.fa} --ploidy 1 {input.bam} > calls/all.vcf"

#"freebayes -f {input.fa} --ploidy 1 {input.bam} > all.vcf"
#"bcftools mpileup --max-depth 200000 -Ou -f {input.fa} {input.bam} | bcftools call --ploidy 1 -p 1 -cv - > {output}"

rule plot_quals:
    input:
        "calls/all.vcf"
    output:
        "plots/quals.svg"
    script:
        "scripts/plot-quals.py"
